### ISSUE TITLE
Add RequestContext.URLParam()

### ISSUE THREAD

**Issue by Pitasi** [maddalax/htmgo#16]
It's a small improvement but right now, from my code, I need to do this:

```go
import (
	"github.com/go-chi/chi/v5"
	"github.com/maddalax/htmgo/framework/h"
)

func MyPage(ctx *h.RequestContext) *h.Page {
	id := chi.URLParam(ctx.Request, "id")
	...
}
```

While it'd be great to just have a utility method such as:

```go
import (
	"github.com/maddalax/htmgo/framework/h"
)

func MyPage(ctx *h.RequestContext) *h.Page {
	id := ctx.URLParam("id")
	...
}
```

**Comment by maddalax** [comment]
Absolutely can add those. Any other context methods you can think of that may be useful? 

I'll be adding some htmx specific ones too such as isHxRequest, hxTrigger, etc
