### ISSUE TITLE
GetPartialPath doesn't work from subpaths

### ISSUE THREAD

**Issue by Pitasi** [maddalax/htmgo#17]
If I have a page at http://localhost:3000/sub/something and I try to render a partial, it actually makes a request to `http://localhost:3000/sub/mymodname/partials.FooPartial` instead of `http://localhost:3000/mymodname/partials.FooPartial`, getting a 404.

I didn't try it but I think that the fix here could be adding a prefixing slash to this function:

```go
func GetPartialPath(partial PartialFunc) string {
        return "/" + runtime.FuncForPC(reflect.ValueOf(partial).Pointer()).Name()
}
```

**Comment by maddalax** [comment]
Fixed: https://github.com/maddalax/htmgo/releases/tag/v0.3.4
