### ISSUE TITLE
add validation to the ast gen tool

### ISSUE THREAD

**Issue by maddalax** [maddalax/htmgo#2]
1. it should make sure the project directory is correct
2. should ensure there is a go.mod file

**Comment by rafaelDev0ps** [comment]
hey let me help! I would like to work on this issue!

**Comment by maddalax** [comment]
> hey let me help! I would like to work on this issue!

sure I'd love that! let me know if you have any questions

p.s. feel free to refactor / cleanup the AST code if you so please, its a little messy at the moment @rafaelDev0ps

**Comment by rafaelDev0ps** [comment]
PS. I believe it would be better do the refactoring in other PR

**Comment by maddalax** [comment]
yep!
