### ISSUE TITLE
nice things to have

### ISSUE THREAD

**Issue by maddalax** [maddalax/htmgo#3]
1. constants for trigger types (keyup, click, interval, keycode (enter key), etc

**Comment by sdil** [comment]
is there's a way for me to use loading states or spinner using htmgo?

**Comment by maddalax** [comment]
@sdil Yes of course, I just published a new example to the site showing you how you could do that.

demo: https://htmgo.dev/form
source: https://github.com/maddalax/htmgo/blob/master/htmgo-site/pages/form.go
