### ISSUE TITLE
add html tag to pages

### ISSUE THREAD

**Issue by David-Kalashir** [maddalax/htmgo#30]
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”
all of the pages have this warning.
and this 
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [markup.js:250:53](resource://devtools/server/actors/highlighters/utils/markup.js)

**Comment by maddalax** [comment]
This has been fixed https://github.com/maddalax/htmgo/commit/bb9fb0b327e4e7adeba03f3518e0029b0d7bdcc4
