### ISSUE TITLE
Health endpoint 

### ISSUE THREAD

**Issue by gedw99** [maddalax/htmgo#36]
Could we add a built in health endpoint so that it can be used with deployment ls that rely on it liveliness ?

**Comment by maddalax** [comment]
Possibly, but health endpoints usually consult specific external services that your app uses as well. I likely won't make one built into the framework, but I could add one to the starter template

**Comment by maddalax** [comment]
<img width="910" alt="Screenshot 2024-10-24 at 8 56 33 AM" src="https://github.com/user-attachments/assets/9fb0d982-f3b7-4dae-a955-5db49c53c22d">

You should also be able to just add one quickly inside the register function
