### ISSUE TITLE
Keeps crashing on windows go version 1.23.0

### ISSUE THREAD

**Issue by JohnKinyanjui** [maddalax/htmgo#56]
Running in watch mode
Starting processes...
Generating CSS...
Starting server...
# test/__htmgo
__htmgo\pages-generated.go:16:37: cannot use cc (variable of type *h.RequestContext) as h.Ren value in argument to pages.RootPage: *h.RequestContext does not implement h.Ren (missing method Render)

**Comment by JohnKinyanjui** [comment]
ok thanks for the good work

**Comment by JohnKinyanjui** [comment]
I have it tested now its working on windows ty

**Comment by maddalax** [comment]
@JohnKinyanjui just fyi I noticed a few more issues on windows as im testing it now and I just pushed fixes. You'll need to run the same commands above to get new cli version

Seems there was an issue with killing processes for htmgo watch

**Comment by JohnKinyanjui** [comment]
Did it, thanks for the update
