### ISSUE TITLE
Integrating with an Existing Echo Backends

### ISSUE THREAD

**Issue by JohnKinyanjui** [maddalax/htmgo#6]
can we intergrate it as a library if possible in echo if possible, also great echo keep up the great work

**Comment by maddalax** [comment]
hi see here: https://github.com/maddalax/htmgo/pull/7, I'm planning on removing Echo as a requirement and replacing it with the std lib

**Comment by JohnKinyanjui** [comment]
ok thanks i will be waiting

**Comment by maddalax** [comment]
This has been merged and is in release 0.3.0
