### ISSUE TITLE
Tailwind Exits when you run 'htmgo watch'

### ISSUE THREAD

**Issue by JohnKinyanjui** [maddalax/htmgo#67]
When you run htmgo watch tailwind crashes

```bash
2024/11/01 13:45:02 ERROR Error running command:  error="exit status 1" command=tailwind
```

**Comment by maddalax** [comment]
If you create a fresh new project with the starter template, does it work? What OS are you on, windows right?

**Comment by JohnKinyanjui** [comment]
Yes am on windows, I created a new project tried it still giving the same error now

**Comment by JohnKinyanjui** [comment]
also with this

```bash
2024/11/01 14:50:54 Failed to format source: 4:26: unknown escape sequence (and 4 more errors)
```

**Comment by maddalax** [comment]
> Yes am on windows, I created a new project tried it still giving the same error now

@JohnKinyanjui Can you try updating the htmgo cli again and try a new project?

```
set GOPROXY=direct go install github.com/maddalax/htmgo/cli/htmgo@latest
```

**Comment by JohnKinyanjui** [comment]
```bash
Running in watch mode
Starting processes...
Generating CSS...
2024/11/01 15:14:35 Failed to format source: 4:26: unknown escape sequence (and 5 more errors)

Starting server...
__htmgo\assets\assets-generated.go:1:1: expected 'package', found 'EOF'

```

did that now this is the error and even set the package name the functions for assets do not exists

**Comment by maddalax** [comment]
> ```shell
> Running in watch mode
> Starting processes...
> Generating CSS...
> 2024/11/01 15:14:35 Failed to format source: 4:26: unknown escape sequence (and 5 more errors)
> 
> Starting server...
> __htmgo\assets\assets-generated.go:1:1: expected 'package', found 'EOF'
> ```
> 
> did that now this is the error and even set the package name the functions for assets do not exists

Are you sure it updated? Can you try re-running it again

```
set GOPROXY=direct && go install github.com/maddalax/htmgo/cli/htmgo@latest
```

**Comment by maddalax** [comment]
https://github.com/user-attachments/assets/72c894bd-2a7f-41ad-90e6-362c0a601ed7

I just spun up the template on my windows vm and it is working for me. Are you on windows 11? Whats your go version?

**Comment by JohnKinyanjui** [comment]
i switched up to WSL it seems to be working fine, for windows i think there an issue with getting the latest package 

![Screenshot 2024-11-01 152207](https://github.com/user-attachments/assets/bde10eef-b166-489a-9c9a-34245eece48d)

**Comment by JohnKinyanjui** [comment]
also am using ```go version go1.23.2 windows/amd64``` , i just uninstalled the whole package and reinstalled it again it now working

**Comment by JohnKinyanjui** [comment]
yah it seemed that way, thanks also for the help, that will be really helpful in the long run
