### ISSUE TITLE
How to use  Chat App Using SSE 

### ISSUE THREAD

**Issue by samunnoi** [maddalax/htmgo#80]
I don't use Chat App Using SSE in example  project

**Comment by maddalax** [comment]
What are you trying to do?

**Comment by samunnoi** [comment]
Chat

**Comment by Jipok** [comment]
https://htmgo.dev/docs/pushing-data/examples/chat
404

**Comment by maddalax** [comment]
ah, will fix, it should be https://htmgo.dev/examples/chat

**Comment by Jipok** [comment]
@maddalax 
There is a bug. I create a chat, copy the link. I open it in a private window. The chat opens, but there are no messages, no user list, and nothing is sent.

![изображение](https://github.com/user-attachments/assets/eed8cc4a-665a-4ce7-aaeb-d03f2af45a84)
