### ISSUE TITLE
cannabalized libs - seek to align

### ISSUE THREAD

**Issue by nicosql** [maddalax/htmgo#92]
have you seen this? https://github.com/ZEISS/fiber-htmx

no offense but this seems to me a superior implementation in every way, selfishly hoping you can either steal some ideas here (or code) and/or find a way to work with this gentleman.

I think it's only a matter of time before this project overtakes this one given the clash and that you guys show up in all the same searches.

**Comment by maddalax** [comment]
lmao troll?
